# Generated by Django 2.2.16 on 2020-11-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0038_product_authorized_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='authorized_groups',
        ),
    ]
