# Generated by Django 2.2.16 on 2020-11-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0039_remove_product_authorized_groups'),
        ('dojo', '0060_false_p_dedupe_indices'),
    ]

    operations = [
    ]
